# Generated by Django 2.2.2 on 2019-06-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up_conv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='complaint_id',
        ),
    ]
